### ISSUE TITLE
Procedural Recommendations

### ISSUE THREAD

**Issue by AnsataMamoru** [sking68/DescartesInterpreter#10]
- Symbol Table
Should be created, and be empty at the beginning of the program, and passed around or globally accessible?

- Operators
Jumping through methods, or traveling through switch statements(?)

- Assign
Acquire first in list, put onto stack.
Observe assign command, call assign method, passing list from node(?), and top value of the stack.(?), symbol table(?)
Compute/finish/acquire value from right hand side of the assign operator, and either return this value to be assigned to the left value, or update the symbol table, then return the symbol table.

**Comment by sking68** [comment]
* symbolTable is static and accessible to all subclasses

* The tree is interpreted recursively

* Assign updates the symbol table. Then when IDs are used, their values can be looked up from the symbol table
